import streamlit as st
import pandas as pd
import os

# Full attendee list extracted from the conference document
ATTENDEE_DATA = [
    {"First Name": "Lucy", "Last Name": "Rigby KC MP", "Job Title": "Economic Secretary to the Treasury", "Organisation": "HM Treasury"},
    {"First Name": "Tom", "Last Name": "Bentley", "Job Title": "CRO", "Organisation": "10x Banking"},
    {"First Name": "Nikhil", "Last Name": "Sengupta", "Job Title": "Business Development Director", "Organisation": "10x Banking"},
    {"First Name": "Simon", "Last Name": "Black", "Job Title": "Managing Partner", "Organisation": "1805 Ltd"},
    {"First Name": "Stacey Ann", "Last Name": "Mitchinson", "Job Title": "Director of Operations", "Organisation": "1st Class Credit Union"},
    {"First Name": "Gayle", "Last Name": "Lloyd", "Job Title": "CEO", "Organisation": "1st Class Credit Union"},
    {"First Name": "Robert", "Last Name": "Hall", "Job Title": "Director", "Organisation": "1st Class Credit Union"},
    {"First Name": "Bruce", "Last Name": "Devenport", "Job Title": "Chair", "Organisation": "1st Class Credit Union"},
    {"First Name": "Jim", "Last Name": "McNicholls", "Job Title": "Board Member", "Organisation": "1st Class Credit Union"},
    {"First Name": "Geoff", "Last Name": "Poulter", "Job Title": "Cyber SME", "Organisation": "A Jolly Consulting"},
    {"First Name": "Matthew", "Last Name": "Neall", "Job Title": "Director", "Organisation": "A Jolly Consulting"},
    {"First Name": "Krysta", "Last Name": "Collin", "Job Title": "Manager", "Organisation": "A Jolly Consulting"},
    {"First Name": "Matt", "Last Name": "Bland", "Job Title": "Chief Executive", "Organisation": "ABCUL"},
    {"First Name": "Tom", "Last Name": "Mack", "Job Title": "Business Development Rep - UK & Nordics", "Organisation": "ACI Worldwide"},
    {"First Name": "Richard", "Last Name": "Albery", "Job Title": "Head of UK & Ireland", "Organisation": "ACI Worldwide"},
    {"First Name": "Simon", "Last Name": "Lofthouse", "Job Title": "Partner", "Organisation": "Addleshaw Goddard LLP"},
    {"First Name": "Ben", "Last Name": "Koehne", "Job Title": "Partner", "Organisation": "Addleshaw Goddard LLP"},
    {"First Name": "Rosanna", "Last Name": "Bryant", "Job Title": "Partner", "Organisation": "Addleshaw Goddard LLP"},
    {"First Name": "David", "Last Name": "Pygott", "Job Title": "Partner", "Organisation": "Addleshaw Goddard LLP"},
    {"First Name": "Priscilla", "Last Name": "Hetherton", "Job Title": "Legal Director", "Organisation": "Addleshaw Goddard LLP"},
    {"First Name": "Mark", "Last Name": "Hallam", "Job Title": "Partner", "Organisation": "Addleshaw Goddard LLP"},
    {"First Name": "Alex", "Last Name": "Valy", "Job Title": "Designer", "Organisation": "Alex Valy Design"},
    {"First Name": "Archie", "Last Name": "Dickinson", "Job Title": "Senior Manager Advisory and Funding", "Organisation": "Allia C&C"},
    {"First Name": "Crispin", "Last Name": "Pugh", "Job Title": "Sales Trader", "Organisation": "Allia C&C"},
    {"First Name": "Luke", "Last Name": "DiRollo", "Job Title": "CEP", "Organisation": "ALMIS International"},
    {"First Name": "Jake", "Last Name": "Rose", "Job Title": "Chief Commercial Officer", "Organisation": "ALMIS International"},
    {"First Name": "Neil", "Last Name": "Irvine-Hess", "Job Title": "Head of Implementation", "Organisation": "ALMIS International"},
    {"First Name": "Emma", "Last Name": "Farrugia", "Job Title": "Product Owner", "Organisation": "ALMIS International"},
    {"First Name": "Sophie", "Last Name": "Scott", "Job Title": "Product Owner", "Organisation": "ALMIS International"},
    {"First Name": "Deborah", "Last Name": "Dray", "Job Title": "Account Manager", "Organisation": "ALMIS International"},
    {"First Name": "James", "Last Name": "Scott", "Job Title": "CP Exec", "Organisation": "AND Digital"},
    {"First Name": "Amy", "Last Name": "Cockram", "Job Title": "Club Exec", "Organisation": "AND Digital"},
    {"First Name": "Eran", "Last Name": "Baram", "Job Title": "M&A Manager", "Organisation": "Andromeda"},
    {"First Name": "Gearoid", "Last Name": "Power", "Job Title": "CEO", "Organisation": "Antuar"},
    {"First Name": "Rahul", "Last Name": "Sisodia", "Job Title": "Director", "Organisation": "Apex Software Solutions Ltd"},
    {"First Name": "James", "Last Name": "Pagan", "Job Title": "Director of Product & Portfolio Management", "Organisation": "April Mortgages"},
    {"First Name": "Jim", "Last Name": "Murphy", "Job Title": "Founder and Executive Chair", "Organisation": "Arden Strategies"},
    {"First Name": "Ellie", "Last Name": "Miller", "Job Title": "Managing Director of External Affairs", "Organisation": "Arden Strategies"},
    {"First Name": "Andrew", "Last Name": "Whyte", "Job Title": "Chief Executive", "Organisation": "Association of Financial Mutuals"},
    {"First Name": "Stephanie", "Last Name": "Charman", "Job Title": "Chief Executive", "Organisation": "Association of Mortgage Intermediaries"},
    {"First Name": "Christian", "Last Name": "Konig", "Job Title": "Managing Director", "Organisation": "Association of Private Bausparkassen"},
    {"First Name": "Max", "Last Name": "Lesemann", "Job Title": "Head of Banking Regulation", "Organisation": "Association of Private Bausparkassen"},
    {"First Name": "Jonathan", "Last Name": "Stallard", "Job Title": "Regional Director", "Organisation": "Backbase"},
    {"First Name": "Frederico", "Last Name": "Venturieri", "Job Title": "Head of Partnerships & Alliances", "Organisation": "Backbase"},
    {"First Name": "Richard", "Last Name": "Waghorn", "Job Title": "Business Development Manager", "Organisation": "Backbase"},
    {"First Name": "Jacqui", "Last Name": "Ashe", "Job Title": "Head of Division, Analytics & Mutuals", "Organisation": "Bank of England"},
    {"First Name": "Charlotte", "Last Name": "Gerken", "Job Title": "Executive Director", "Organisation": "Bank of England"},
    {"First Name": "Chris", "Last Name": "Donald", "Job Title": "Prudential Regulation", "Organisation": "Bank of England"},
    {"First Name": "Andrew", "Last Name": "Wilkie", "Job Title": "Director", "Organisation": "Baringa Partners"},
    {"First Name": "David", "Last Name": "Harris", "Job Title": "Partner", "Organisation": "Baringa Partners"},
    {"First Name": "Paul", "Last Name": "Mihajlovic", "Job Title": "Partner", "Organisation": "Baringa Partners"},
    {"First Name": "Sarah", "Last Name": "Applegarth", "Job Title": "Director", "Organisation": "Baringa Partners"},
    {"First Name": "Richard", "Last Name": "Ingle", "Job Title": "Chief Executive", "Organisation": "Bath Building Society"},
    {"First Name": "Emma", "Last Name": "Davis", "Job Title": "Chief Customer Officer", "Organisation": "Bath Building Society"},
    {"First Name": "Andrew", "Last Name": "Payton", "Job Title": "Non-Executive Director", "Organisation": "Bath Building Society"},
    {"First Name": "Steve", "Last Name": "Burnard", "Job Title": "Chief Digital Officer", "Organisation": "Bath Building Society"},
    {"First Name": "Craig", "Last Name": "Brown", "Job Title": "Chief Mortgage Officer", "Organisation": "Bath Building Society"},
    {"First Name": "Paul", "Last Name": "Gilbert", "Job Title": "Partner", "Organisation": "BDO"},
    {"First Name": "Jen", "Last Name": "Hale", "Job Title": "Partner", "Organisation": "BDO"},
    {"First Name": "Tim", "Last Name": "Lawrence", "Job Title": "Partner", "Organisation": "BDO"},
    {"First Name": "Sarah", "Last Name": "Collins", "Job Title": "Director", "Organisation": "BDO"},
    {"First Name": "James", "Last Name": "Billingham", "Job Title": "Partner", "Organisation": "BDO"},
    {"First Name": "Graham", "Last Name": "FitzGerald", "Job Title": "Business Development Director", "Organisation": "Be Inspirational Group"},
    {"First Name": "Janet", "Last Name": "Bedford", "Job Title": "Chief Executive", "Organisation": "Beverley Building Society"},
    {"First Name": "Kevin", "Last Name": "Mowles", "Job Title": "Chief Operations Officer", "Organisation": "Beverley Building Society"},
    {"First Name": "Sally", "Last Name": "Hall", "Job Title": "Chief Financial Officer", "Organisation": "Beverley Building Society"},
    {"First Name": "Karen", "Last Name": "Wint", "Job Title": "Non-Executive Director", "Organisation": "Beverley Building Society"},
    {"First Name": "Bob", "Last Name": "Andrews", "Job Title": "Non-Executive Director", "Organisation": "Beverley Building Society"},
    {"First Name": "Guru", "Last Name": "Vaidyanathan", "Job Title": "Principal", "Organisation": "Boston Consulting Group"},
    {"First Name": "Sukand", "Last Name": "Ramachandran", "Job Title": "Managing Director", "Organisation": "Boston Consulting Group"},
    {"First Name": "Brendan", "Last Name": "Gilmore", "Job Title": "Managing Director", "Organisation": "BPG Strategy"},
    {"First Name": "Emily", "Last Name": "Gore", "Job Title": "VP Business Development & Strategy", "Organisation": "Broadridge"},
    {"First Name": "Brendan", "Last Name": "Carter", "Job Title": "Marketing Specialist", "Organisation": "Broadridge"},
    {"First Name": "Joseph", "Last Name": "Oakenfold", "Job Title": "Sales Director", "Organisation": "Broadridge"},
    {"First Name": "Dominic", "Last Name": "Rix", "Job Title": "Senior Director, Account Management", "Organisation": "Broadridge"},
    {"First Name": "Barney", "Last Name": "Hosey", "Job Title": "General Manager, Signal", "Organisation": "Broadridge"},
    {"First Name": "Karen", "Last Name": "Scrimgeour", "Job Title": "Senior Consultant", "Organisation": "Broadridge"},
    {"First Name": "Dan", "Last Name": "Wass", "Job Title": "CEO", "Organisation": "Buckinghamshire Building Society"},
    {"First Name": "Jason", "Last Name": "Russell", "Job Title": "Head of Events", "Organisation": "Building Societies Association"},
    {"First Name": "Robert", "Last Name": "Thickett", "Job Title": "Policy Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Tracey", "Last Name": "Ward", "Job Title": "Events Co-ordinator", "Organisation": "Building Societies Association"},
    {"First Name": "Christie", "Last Name": "Hall", "Job Title": "Events Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Ruth", "Last Name": "Doubleday", "Job Title": "Head of Prudential Regulation", "Organisation": "Building Societies Association"},
    {"First Name": "Joanna", "Last Name": "Quirk", "Job Title": "Head of Operations", "Organisation": "Building Societies Association"},
    {"First Name": "Fergus", "Last Name": "Hamilton Collard", "Job Title": "Policy Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Andrew", "Last Name": "Hopkins", "Job Title": "Policy Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Elaine", "Last Name": "Morton", "Job Title": "Head of Legal, Conduct Risk & Crime", "Organisation": "Building Societies Association"},
    {"First Name": "Matthew", "Last Name": "Ball", "Job Title": "Public Affairs Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Laura", "Last Name": "Magezi", "Job Title": "Policy Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Sarah", "Last Name": "Harrison CB MBE", "Job Title": "Chief Executive", "Organisation": "Building Societies Association"},
    {"First Name": "Katie", "Last Name": "Wise", "Job Title": "Channels Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Georgia", "Last Name": "Elliott", "Job Title": "Policy Analyst", "Organisation": "Building Societies Association"},
    {"First Name": "Debbie", "Last Name": "Enever", "Job Title": "Head of External Affairs", "Organisation": "Building Societies Association"},
    {"First Name": "Tanya", "Last Name": "Jackson", "Job Title": "External Affairs", "Organisation": "Building Societies Association"},
    {"First Name": "Paul", "Last Name": "Broadhead", "Job Title": "Head of Mortgage and Housing Policy", "Organisation": "Building Societies Association"},
    {"First Name": "Joseph", "Last Name": "Thompson", "Job Title": "Economist", "Organisation": "Building Societies Association"},
    {"First Name": "Amanda", "Last Name": "Esteban", "Job Title": "PA", "Organisation": "Building Societies Association"},
    {"First Name": "Andrew", "Last Name": "Gall", "Job Title": "Head of Savings & Economics", "Organisation": "Building Societies Association"},
    {"First Name": "Grant", "Last Name": "Leech", "Job Title": "Event Staff", "Organisation": "Building Societies Association"},
    {"First Name": "Inger", "Last Name": "Stevenson", "Job Title": "Event Staff", "Organisation": "Building Societies Association"},
    {"First Name": "Pamela", "Last Name": "Gladstone", "Job Title": "Event Staff", "Organisation": "Building Societies Association"},
    {"First Name": "Yvonne", "Last Name": "Campbell", "Job Title": "Event Staff", "Organisation": "Building Societies Association"},
    {"First Name": "Isabelle", "Last Name": "Conroy", "Job Title": "Event Staff", "Organisation": "Building Societies Association"},
    {"First Name": "James", "Last Name": "Stewart", "Job Title": "Event Staff", "Organisation": "Building Societies Association"},
    {"First Name": "Abigail", "Last Name": "Woodrow", "Job Title": "Policy Manager", "Organisation": "Building Societies Association"},
    {"First Name": "Svea", "Last Name": "Mielk", "Job Title": "Student", "Organisation": "BVR"},
    {"First Name": "Malin", "Last Name": "Mielk", "Job Title": "Student", "Organisation": "BVR"},
    {"First Name": "Melina", "Last Name": "Morrison", "Job Title": "CEO", "Organisation": "Business Council Co-operatives and Mutuals"},
    {"First Name": "Thorsten", "Last Name": "Reinicke", "Job Title": "Advisor", "Organisation": "BVR"},
    {"First Name": "Catherine", "Last Name": "Bellingham", "Job Title": "Microsoft Sales Specialist", "Organisation": "Bytes"},
    {"First Name": "Louis", "Last Name": "Macey", "Job Title": "Account Manager", "Organisation": "Bytes"},
    {"First Name": "Sandhya", "Last Name": "Kawar", "Job Title": "Chief Risk Officer", "Organisation": "Cambridge Building Society"},
    {"First Name": "Peter", "Last Name": "Burrows", "Job Title": "Chief Executive", "Organisation": "Cambridge Building Society"},
    {"First Name": "Stephen", "Last Name": "O'Donnell", "Job Title": "Non Executive Director", "Organisation": "Cambridge Building Society"},
    {"First Name": "Victoria", "Last Name": "Filler", "Job Title": "Head of Customer Engagement", "Organisation": "Cambridge Building Society"},
    {"First Name": "Sarah", "Last Name": "Green", "Job Title": "Managing Director", "Organisation": "Capita plc"},
    {"First Name": "Amanda", "Last Name": "Partington", "Job Title": "Executive Assistant", "Organisation": "Capita plc"},
    {"First Name": "Samantha", "Last Name": "Homer", "Job Title": "CEO", "Organisation": "Capital Credit Union"},
    {"First Name": "Laura", "Last Name": "Flanagan", "Job Title": "Director of Finance & Compliance", "Organisation": "Capital Credit Union"},
    {"First Name": "Mark", "Last Name": "McAlpine", "Job Title": "Director", "Organisation": "Capital Credit Union"},
    {"First Name": "Rory", "Last Name": "Gaffney", "Job Title": "Chief Operating Officer", "Organisation": "Capital Credit Union"},
    {"First Name": "Liam", "Last Name": "Boyle", "Job Title": "Director", "Organisation": "Capital Credit Union"},
    {"First Name": "Stuart", "Last Name": "Pratt", "Job Title": "Chair", "Organisation": "CBS Change Partners"},
    {"First Name": "Eddie", "Last Name": "Curran", "Job Title": "Founder and Lead Partner", "Organisation": "CBS Change Partners"},
    {"First Name": "Kevin", "Last Name": "Withers", "Job Title": "Change Partner", "Organisation": "CBS Change Partners"},
    {"First Name": "Ros", "Last Name": "Taylor", "Job Title": "Head of PMO Services", "Organisation": "CBS Change Partners"},
    {"First Name": "Mark", "Last Name": "Pridham", "Job Title": "Change Partner", "Organisation": "CBS Change Partners"},
    {"First Name": "Kimberley", "Last Name": "Roberts", "Job Title": "Account Director", "Organisation": "CGI"},
    {"First Name": "Kim", "Last Name": "Roby", "Job Title": "Customer Services Director", "Organisation": "Chorley Building Society"},
    {"First Name": "David", "Last Name": "Shelley", "Job Title": "COO/CFO", "Organisation": "Chorley Building Society"},
    {"First Name": "Becky", "Last Name": "Quirk", "Job Title": "Head of Transformation", "Organisation": "Chorley Building Society"},
    {"First Name": "Sophie", "Last Name": "Bell", "Job Title": "Lead Finance Business Partner", "Organisation": "Co-operative Bank"},
    {"First Name": "Jen", "Last Name": "Bolton", "Job Title": "Head of Commercial Lending", "Organisation": "Co-operative Bank"},
    {"First Name": "Ryan", "Last Name": "Ellis", "Job Title": "Head of Treasury Markets", "Organisation": "Co-operative Bank"},
    {"First Name": "Siobhan", "Last Name": "Evans", "Job Title": "Savings Product Manager", "Organisation": "Co-operative Bank"},
    {"First Name": "Richard", "Last Name": "Morley", "Job Title": "Director of Commercial Lending", "Organisation": "Co-operative Bank"},
    {"First Name": "Leanne", "Last Name": "White", "Job Title": "Head of Customer Operations", "Organisation": "Co-operative Bank"},
    {"First Name": "James", "Last Name": "Dady", "Job Title": "Policy Officer", "Organisation": "Co-operatives UK"},
    {"First Name": "Joe", "Last Name": "McNulty", "Job Title": "Head of Business Development", "Organisation": "CoCo Global"},
    {"First Name": "Beth", "Last Name": "Pavey", "Job Title": "Account Executive", "Organisation": "CoCo Global"},
    {"First Name": "Chris", "Last Name": "Lucas", "Job Title": "Consultant", "Organisation": "CoCo Global"},
    {"First Name": "Annabel", "Last Name": "Bestford", "Job Title": "Account Executive", "Organisation": "CoCo Global"},
    {"First Name": "Chris", "Last Name": "Coe", "Job Title": "Founder", "Organisation": "CoCo Global"},
    {"First Name": "Neil", "Last Name": "Macleod", "Job Title": "Managing Director", "Organisation": "CoCo Global"},
    {"First Name": "Madhukar", "Last Name": "Sharma", "Job Title": "Account Director", "Organisation": "Coforge"},
    {"First Name": "Abdul", "Last Name": "Khan", "Job Title": "General Manager-Mortgages", "Organisation": "Cognizant"},
    {"First Name": "Lindsey", "Last Name": "Rogerson", "Job Title": "Compliance Specialist", "Organisation": "Compliance Corylated"},
    {"First Name": "James", "Last Name": "Fox", "Job Title": "Sales Director", "Organisation": "Connexica"},
    {"First Name": "Marc", "Last Name": "Sutton", "Job Title": "Commercial Director", "Organisation": "Connexica"},
    {"First Name": "Alex", "Last Name": "Hurley", "Job Title": "Solutions Director", "Organisation": "Connexica"},
    {"First Name": "Paul", "Last Name": "D'Ambra", "Job Title": "CEO", "Organisation": "Consectus Ltd"},
    {"First Name": "Santosh", "Last Name": "Singh", "Job Title": "CTO", "Organisation": "Consectus Ltd"},
    {"First Name": "Ian", "Last Name": "Meharg", "Job Title": "Associate Director", "Organisation": "Consectus Ltd"},
    {"First Name": "David", "Last Name": "Spencer", "Job Title": "Non Executive Director", "Organisation": "Consectus Ltd"},
    {"First Name": "Anita", "Last Name": "Singh", "Job Title": "Executive Assistant", "Organisation": "Consectus Ltd"},
    {"First Name": "Henry", "Last Name": "Varney", "Job Title": "Solution Architect", "Organisation": "Consectus Ltd"},
    {"First Name": "Scott", "Last Name": "Wilson", "Job Title": "Founder & CEO", "Organisation": "Covecta"},
    {"First Name": "Ben", "Last Name": "Thomas", "Job Title": "Founder & CRO", "Organisation": "Covecta"},
    {"First Name": "Mark", "Last Name": "Hammond", "Job Title": "Software Engineer", "Organisation": "Covecta"},
    {"First Name": "Tom", "Last Name": "Byrne", "Job Title": "Software Engineer", "Organisation": "Covecta"},
    {"First Name": "Harry", "Last Name": "Powell", "Job Title": "Director of Data Science", "Organisation": "Covecta"},
    {"First Name": "Tanaya", "Last Name": "Jasubhai", "Job Title": "Product Manager", "Organisation": "Covecta"},
    {"First Name": "Lawrence", "Last Name": "Vousden", "Job Title": "Head of Public Affairs", "Organisation": "Coventry Building Society"},
    {"First Name": "Steve", "Last Name": "Hughes", "Job Title": "Group CEO", "Organisation": "Coventry Building Society"},
    {"First Name": "Nic", "Last Name": "Heffernan", "Job Title": "Group Strategy Director", "Organisation": "Coventry Building Society"},
    {"First Name": "Harry", "Last Name": "Walker", "Job Title": "Public Affairs Assistant", "Organisation": "Coventry Building Society"},
    {"First Name": "David", "Last Name": "Thorburn", "Job Title": "Chairman", "Organisation": "Coventry Building Society"},
    {"First Name": "Rachel", "Last Name": "Macfarlane", "Job Title": "Group General Counsel", "Organisation": "Coventry Building Society"},
    {"First Name": "Gary", "Last Name": "Jones", "Job Title": "Group Chief Operations Officer", "Organisation": "Coventry Building Society"},
    {"First Name": "Lanre", "Last Name": "Afuye", "Job Title": "Group Strategy Lead", "Organisation": "Coventry Building Society"},
    {"First Name": "Anna", "Last Name": "Cuskin", "Job Title": "Group Corporate Comms Manager", "Organisation": "Coventry Building Society"},
    {"First Name": "Chris", "Last Name": "Davidson", "Job Title": "Public Affairs Officer", "Organisation": "Coventry Building Society"},
    {"First Name": "Kelly", "Last Name": "Gemmell", "Job Title": "Group Corporate Comms Manager", "Organisation": "Coventry Building Society"},
    {"First Name": "Laura", "Last Name": "Harvey-Ricketts", "Job Title": "Group Treasury Comms Manager", "Organisation": "Coventry Building Society"},
    {"First Name": "Sam", "Last Name": "Roberts", "Job Title": "Treasury Associate", "Organisation": "Coventry Building Society"},
    {"First Name": "Dawn", "Last Name": "Warmington", "Job Title": "Executive Assistant", "Organisation": "Coventry Building Society"},
    {"First Name": "Chris", "Last Name": "Wightman", "Job Title": "Strategy Manager", "Organisation": "Coventry Building Society"},
    {"First Name": "Pedro", "Last Name": "Amaro", "Job Title": "Channel Sales Manager", "Organisation": "Creatio"},
    {"First Name": "Gregor", "Last Name": "Gerick", "Job Title": "Account Executive", "Organisation": "Creatio"},
    {"First Name": "Jay", "Last Name": "Brigden", "Job Title": "Account Executive", "Organisation": "Creatio"},
    {"First Name": "Luke", "Last Name": "Broadhurst", "Job Title": "CEO", "Organisation": "Credit Strategy"},
    {"First Name": "Caroline", "Last Name": "Cope", "Job Title": "Head of Banking UK", "Organisation": "CRIF"},
    {"First Name": "Ian", "Last Name": "Howe", "Job Title": "Sales Director", "Organisation": "CRIF"},
    {"First Name": "Alessandro", "Last Name": "Vilardi", "Job Title": "Regional Manager", "Organisation": "CRIF"},
    {"First Name": "David", "Last Name": "Titterton", "Job Title": "Director", "Organisation": "Crosstide Consulting"},
    {"First Name": "Alex", "Last Name": "Hindson", "Job Title": "Partner, Consulting", "Organisation": "Crowe UK"},
    {"First Name": "Joanne", "Last Name": "Hall", "Job Title": "Head of PR", "Organisation": "Crowe UK"},
    {"First Name": "Kellen", "Last Name": "Farmer", "Job Title": "Director, Consulting", "Organisation": "Crowe UK"},
    {"First Name": "Mustafa", "Last Name": "Iqbal", "Job Title": "Partner, Consulting", "Organisation": "Crowe UK"},
    {"First Name": "Arqam", "Last Name": "Mir", "Job Title": "Assistant Manager, Consulting", "Organisation": "Crowe UK"},
    {"First Name": "Rita", "Last Name": "Machado", "Job Title": "Consultant", "Organisation": "Crowe UK"},
    {"First Name": "Simon", "Last Name": "Morgan", "Job Title": "Financial Services Director", "Organisation": "CSI Ltd"},
    {"First Name": "Amir", "Last Name": "Mirfakhraee", "Job Title": "Enterprise Sales Manager", "Organisation": "CSI Ltd"},
    {"First Name": "Stuart", "Last Name": "Miller", "Job Title": "CEO", "Organisation": "Cumberland Building Society"},
    {"First Name": "Richard", "Last Name": "Ellison", "Job Title": "Chief Customer Officer", "Organisation": "Cumberland Building Society"},
    {"First Name": "Jackie", "Last Name": "Arnold", "Job Title": "NED", "Organisation": "Cumberland Building Society"},
    {"First Name": "Anna", "Last Name": "Barsby", "Job Title": "NED", "Organisation": "Cumberland Building Society"},
    {"First Name": "Susanne", "Last Name": "Parry", "Job Title": "COO", "Organisation": "Cumberland Building Society"},
    {"First Name": "Mitch", "Last Name": "Lapworth", "Job Title": "Technical Director", "Organisation": "Curvestone AI"},
    {"First Name": "Nasos", "Last Name": "Papadopoulos", "Job Title": "CEO", "Organisation": "Curvestone AI"},
    {"First Name": "Jonny", "Last Name": "Parkes", "Job Title": "Client Success Director", "Organisation": "CustomerMinds"},
    {"First Name": "Toby", "Last Name": "Lewis", "Job Title": "Head of Threat Analysis", "Organisation": "Darktrace"},
    {"First Name": "Alex", "Last Name": "Windle", "Job Title": "CEO", "Organisation": "Darlington Building Society"},
    {"First Name": "Paul", "Last Name": "Edwards", "Job Title": "COO", "Organisation": "Darlington Building Society"},
    {"First Name": "Michael", "Last Name": "Conville", "Job Title": "Chief Customer Officer", "Organisation": "Darlington Building Society"},
    {"First Name": "Rachel", "Last Name": "Court", "Job Title": "Chair", "Organisation": "Darlington Building Society"},
    {"First Name": "Steven", "Last Name": "Forth", "Job Title": "Chief Risk Officer", "Organisation": "Darlington Building Society"},
    {"First Name": "Christopher", "Last Name": "Hunter", "Job Title": "Chief Financial Officer", "Organisation": "Darlington Building Society"},
    {"First Name": "Duncan", "Last Name": "Asker", "Job Title": "Non-Executive Director", "Organisation": "Darlington Building Society"},
    {"First Name": "Robert", "Last Name": "Sinclair", "Job Title": "Non-Executive Director", "Organisation": "Darlington Building Society"},
    {"First Name": "Ryan", "Last Name": "Taylor", "Job Title": "Practice Lead", "Organisation": "DCR Partners"},
    {"First Name": "Charlotte", "Last Name": "Kendal Parker", "Job Title": "Practice Lead", "Organisation": "DCR Partners"},
    {"First Name": "Chloe", "Last Name": "McDonald", "Job Title": "Consultant", "Organisation": "DCR Partners"},
    {"First Name": "Gemma", "Last Name": "Sandford", "Job Title": "Practice Lead", "Organisation": "DCR Partners"},
    {"First Name": "Bryan", "Last Name": "Hurcombe", "Job Title": "Senior Consultant", "Organisation": "DCR Partners"},
    {"First Name": "Raj", "Last Name": "Kohli", "Job Title": "Managing Director", "Organisation": "DCR Partners"},
    {"First Name": "Jason", "Last Name": "John", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Charlotte", "Last Name": "Nordberg", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Chloe", "Last Name": "Seddon", "Job Title": "Director", "Organisation": "Deloitte"},
    {"First Name": "Ashley", "Last Name": "Lewis", "Job Title": "Director", "Organisation": "Deloitte"},
    {"First Name": "Lisa", "Last Name": "Branson", "Job Title": "Director", "Organisation": "Deloitte"},
    {"First Name": "Richard", "Last Name": "Kibble", "Job Title": "Director", "Organisation": "Deloitte"},
    {"First Name": "Russell", "Last Name": "Davis", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Kieren", "Last Name": "Cooper", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Kevin", "Last Name": "Johnson", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Simon", "Last Name": "Judd", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Alex", "Last Name": "Brown", "Job Title": "Associate Director", "Organisation": "Deloitte"},
    {"First Name": "Lyndsey", "Last Name": "Fallon", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Alastair", "Last Name": "Mcgeorge", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Michael", "Last Name": "Robinson", "Job Title": "Partner", "Organisation": "Deloitte"},
    {"First Name": "Donna", "Last Name": "Stapleton", "Job Title": "Business Development", "Organisation": "Deloitte"},
    {"First Name": "Chris", "Last Name": "Wilson", "Job Title": "CEO", "Organisation": "deploy12 Limited"},
    {"First Name": "Raj", "Last Name": "Marwaha", "Job Title": "Managing Director", "Organisation": "Dharma Risk"},
    {"First Name": "Arindom", "Last Name": "Basu", "Job Title": "Chief Commercial Officer", "Organisation": "Digilytics"},
    {"First Name": "Sneha", "Last Name": "Paul", "Job Title": "Analyst", "Organisation": "Digilytics"},
    {"First Name": "Reetwija", "Last Name": "Chakraborty", "Job Title": "Analyst", "Organisation": "Digilytics"},
    {"First Name": "Aroushka", "Last Name": "Jain", "Job Title": "Sales Executive", "Organisation": "Digilytics"},
    {"First Name": "Melissa", "Last Name": "Mathew", "Job Title": "Project Manager", "Organisation": "Digilytics"},
    {"First Name": "Nalin", "Last Name": "Suri", "Job Title": "CEO", "Organisation": "Digilytics"},
    {"First Name": "Leigh", "Last Name": "Carlin", "Job Title": "CCO", "Organisation": "docStribute"},
    {"First Name": "Stuart", "Last Name": "Fearn MBE", "Job Title": "Director of Customer Services", "Organisation": "docStribute"},
    {"First Name": "Chris", "Last Name": "Ansara", "Job Title": "CEO", "Organisation": "docStribute"},
    {"First Name": "Phil", "Last Name": "Shelley", "Job Title": "Chair", "Organisation": "docStribute"},
    {"First Name": "Beth", "Last Name": "Love", "Job Title": "Sales Support", "Organisation": "docStribute"},
    {"First Name": "Manila", "Last Name": "Mclean", "Job Title": "Non Executive Director", "Organisation": "docStribute"},
    {"First Name": "Daniel", "Last Name": "Rose", "Job Title": "Founder", "Organisation": "Doshi"},
    {"First Name": "Simon", "Last Name": "Measday", "Job Title": "Managing Director", "Organisation": "dotConnect-Solutions Limited"},
    {"First Name": "Mohamed", "Last Name": "Gamil", "Job Title": "Lead Solutions Architect", "Organisation": "dotConnect-Solutions Limited"},
    {"First Name": "Saj", "Last Name": "Shahid", "Job Title": "Strategic Advisor", "Organisation": "dotConnect-Solutions Limited"},
    {"First Name": "Matthew", "Last Name": "Lambert", "Job Title": "Principal Architect", "Organisation": "Drova"},
    {"First Name": "Giovanni", "Last Name": "Aracu", "Job Title": "Engagement Manager", "Organisation": "Drova"},
    {"First Name": "Andrew", "Last Name": "Lingley", "Job Title": "Head of Practice", "Organisation": "Drova"},
    {"First Name": "Aline", "Last Name": "Freire", "Job Title": "Relationship Manager", "Organisation": "Drova"},
    {"First Name": "Cécile", "Last Name": "Hopkins", "Job Title": "Delivery Lead", "Organisation": "Drova"},
    {"First Name": "John", "Last Name": "Bozic", "Job Title": "Director", "Organisation": "Duamta"},
    {"First Name": "Claire", "Last Name": "Guy", "Job Title": "Finance Director", "Organisation": "Dudley Building Society"},
    {"First Name": "Sabir", "Last Name": "Damji", "Job Title": "Head of Financial Services UK", "Organisation": "DXC"},
    {"First Name": "Yvonne", "Last Name": "Fraser", "Job Title": "Account Manager", "Organisation": "DXC"},
    {"First Name": "Sleman", "Last Name": "Bakir", "Job Title": "Account Manager", "Organisation": "DXC"},
    {"First Name": "Hari Prasad", "Last Name": "Govindarajan", "Job Title": "Account Manager", "Organisation": "DXC"},
    {"First Name": "Sean James", "Last Name": "O'Beirne", "Job Title": "Sales Lead", "Organisation": "DXC"},
    {"First Name": "Yogesh", "Last Name": "Kshirsagar", "Job Title": "Engagement Director", "Organisation": "DXC"},
    {"First Name": "Richard", "Last Name": "Hibbert", "Job Title": "Delivery Director", "Organisation": "DXC"},
    {"First Name": "Lokesh", "Last Name": "Jhamb", "Job Title": "Transformation Director", "Organisation": "DXC"},
    {"First Name": "Alex", "Last Name": "Robinson", "Job Title": "Chair", "Organisation": "Earl Shilton Building Society"},
    {"First Name": "Louise", "Last Name": "Pryor", "Job Title": "Chair of Board", "Organisation": "Ecology Building Society"},
    {"First Name": "Gareth", "Last Name": "Griffiths", "Job Title": "CEO", "Organisation": "Ecology Building Society"},
    {"First Name": "Helen", "Last Name": "McLoughlin", "Job Title": "Executive Assistant", "Organisation": "Ecology Building Society"},
    {"First Name": "Michael", "Last Name": "Sollitt", "Job Title": "Head of HR", "Organisation": "Ecology Building Society"},
    {"First Name": "Giovanni", "Last Name": "D'Alessio", "Job Title": "Chief Operating Officer", "Organisation": "Ecology Building Society"},
    {"First Name": "Jo", "Last Name": "Norton", "Job Title": "Chief Risk Officer", "Organisation": "Ecology Building Society"},
    {"First Name": "Andy", "Last Name": "Mulligan", "Job Title": "Chief Financial Officer", "Organisation": "Ecology Building Society"},
    {"First Name": "John", "Last Name": "Atkinson", "Job Title": "Managing Director", "Organisation": "Eligible"},
    {"First Name": "Rameez", "Last Name": "Zafar", "Job Title": "Cofounder", "Organisation": "Eligible"},
    {"First Name": "Zahra", "Last Name": "Hassan", "Job Title": "Operations Lead", "Organisation": "Eligible Limited"},
    {"First Name": "Nina", "Last Name": "Schindler", "Job Title": "CEO", "Organisation": "European Association of Co-operative Banks"},
    {"First Name": "Kevin", "Last Name": "Daly", "Job Title": "Product Director", "Organisation": "Experian"},
    {"First Name": "Karl", "Last Name": "Williams", "Job Title": "Sales Manager", "Organisation": "Experian"},
    {"First Name": "Rebecca", "Last Name": "Galvin", "Job Title": "Senior Sales", "Organisation": "Experian"},
    {"First Name": "Connor", "Last Name": "Baxter", "Job Title": "Sales Director", "Organisation": "Experian"},
    {"First Name": "Christopher", "Last Name": "Woolard CBE", "Job Title": "Partner", "Organisation": "EY"},
    {"First Name": "Patsy", "Last Name": "Smithies", "Job Title": "Account Manager", "Organisation": "EY"},
    {"First Name": "Rohit", "Last Name": "Garg", "Job Title": "Partner", "Organisation": "EY"},
    {"First Name": "Michael", "Last Name": "Scoular", "Job Title": "Partner", "Organisation": "EY"},
    {"First Name": "Jacqueline", "Last Name": "Quinn", "Job Title": "Partner", "Organisation": "EY"},
    {"First Name": "Nathalie", "Last Name": "Seager", "Job Title": "Partner", "Organisation": "EY"},
    {"First Name": "Blake", "Last Name": "Adlem", "Job Title": "Director", "Organisation": "EY"},
    {"First Name": "Marion", "Last Name": "Bezak dit Kowalski", "Job Title": "Senior Manager", "Organisation": "EY"},
    {"First Name": "Gary K", "Last Name": "Adams", "Job Title": "Executive Assistant", "Organisation": "EY"},
    {"First Name": "Michael", "Last Name": "Cooke", "Job Title": "Director", "Organisation": "EY"},
    {"First Name": "Clive", "Last Name": "Bowles", "Job Title": "Director", "Organisation": "Fairmort Limited"},
    {"First Name": "Ben", "Last Name": "Etchebarne", "Job Title": "Director", "Organisation": "Fairmort Limited"},
    {"First Name": "Andrew", "Last Name": "Lloyd", "Job Title": "Chief Executive Officer", "Organisation": "Fignum"},
    {"First Name": "Steve", "Last Name": "Carruthers", "Job Title": "Growth Director", "Organisation": "Fignum"},
    {"First Name": "Sarah", "Last Name": "Pritchard", "Job Title": "Deputy Chief Executive", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Samantha", "Last Name": "Barton-Turnbull", "Job Title": "Manager", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Dominic", "Last Name": "Cashman", "Job Title": "Director of Authorisations", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Claire", "Last Name": "Whyte", "Job Title": "Head of Department", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Pamela", "Last Name": "Nunn", "Job Title": "Executive Assistant", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Alex", "Last Name": "Chruscikowski", "Job Title": "Head of Department", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Craig", "Last Name": "Mason", "Job Title": "Manager", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Phoebe", "Last Name": "O'Carroll-Moran", "Job Title": "Manager", "Organisation": "Financial Conduct Authority"},
    {"First Name": "Tina", "Last Name": "Coates", "Job Title": "Stakeholder Manager", "Organisation": "Financial Services Compensation Scheme"},
    {"First Name": "Alison", "Last Name": "Houston", "Job Title": "Stakeholder Manager", "Organisation": "Financial Services Skills Commission"},
    {"First Name": "Jeremy", "Last Name": "Bliss", "Job Title": "Sales Director", "Organisation": "Finastra"},
    {"First Name": "Greg", "Last Name": "Caldwell", "Job Title": "Sales Lead", "Organisation": "Finastra"},
    {"First Name": "Narendra", "Last Name": "Mistry", "Job Title": "Solution Architect", "Organisation": "Finastra"},
    {"First Name": "Matthew", "Last Name": "Woffindin", "Job Title": "Principal Solution Consultant", "Organisation": "Finastra"},
    {"First Name": "Kieran", "Last Name": "O'Dowd", "Job Title": "Sales Director", "Organisation": "Finastra"},
    {"First Name": "Kieron", "Last Name": "O'Toole", "Job Title": "Account Manager", "Organisation": "Finastra"},
    {"First Name": "Gemma", "Last Name": "Bone", "Job Title": "Marketing Manager", "Organisation": "Finova"},
    {"First Name": "Hamza", "Last Name": "Behzad", "Job Title": "Sales Manager", "Organisation": "Finova"},
    {"First Name": "Matt", "Last Name": "Newman", "Job Title": "Product Director", "Organisation": "Finova"},
    {"First Name": "Tom", "Last Name": "Povey", "Job Title": "Strategic Account Director", "Organisation": "Finova"},
    {"First Name": "Marcus", "Last Name": "Bennett", "Job Title": "Enterprise Sales Manager", "Organisation": "Finova"},
    {"First Name": "Rowan", "Last Name": "Clayton", "Job Title": "Head of Product", "Organisation": "Finova"},
    {"First Name": "Richard", "Last Name": "Marsh", "Job Title": "Director of Technology", "Organisation": "Finova"},
    {"First Name": "John", "Last Name": "Tilzey", "Job Title": "Product Manager", "Organisation": "Finova"},
    {"First Name": "Lewis", "Last Name": "Harris", "Job Title": "Product Director", "Organisation": "Finova"},
    {"First Name": "Gareth", "Last Name": "Richardson", "Job Title": "CEO", "Organisation": "Finova"},
    {"First Name": "Rich", "Last Name": "Wainwright", "Job Title": "CEO and Founder", "Organisation": "FinProxy Limited"},
    {"First Name": "Fabio", "Last Name": "Distaso", "Job Title": "Chief Executive Officer", "Organisation": "Finsolutia"},
    {"First Name": "Haris", "Last Name": "Sehic", "Job Title": "Relationship Director", "Organisation": "Finsolutia"},
    {"First Name": "Joshua", "Last Name": "White", "Job Title": "Account Director", "Organisation": "FintechOS"},
    {"First Name": "Enas", "Last Name": "Beseiso", "Job Title": "Sales Development Representative", "Organisation": "FintechOS"},
    {"First Name": "Andrei", "Last Name": "Gaman", "Job Title": "VP Banking", "Organisation": "FintechOS"},
    {"First Name": "Gerry", "Last Name": "Goodwin", "Job Title": "Head of Alliances", "Organisation": "FintechOS"},
    {"First Name": "Roberto", "Last Name": "Zaza", "Job Title": "Sales Executive", "Organisation": "FintechOS"},
    {"First Name": "Mark", "Last Name": "Dearman", "Job Title": "Sales Executive", "Organisation": "FintechOS"},
    {"First Name": "Duncan", "Last Name": "Beatty", "Job Title": "Chief Executive", "Organisation": "Fintilect"},
    {"First Name": "Nick", "Last Name": "Freer", "Job Title": "Director", "Organisation": "Fintilect"},
    {"First Name": "Darion", "Last Name": "Whitford", "Job Title": "Director", "Organisation": "Fintilect"},
    {"First Name": "Bernadette", "Last Name": "Pitt", "Job Title": "Marketing Director", "Organisation": "Fintilect"},
    {"First Name": "Callum", "Last Name": "Brodie", "Job Title": "Associate Director of Marketing", "Organisation": "Fitch Ratings"},
    {"First Name": "Lisa", "Last Name": "Neary", "Job Title": "VP, Financial Services", "Organisation": "Fitch Ratings"},
    {"First Name": "Ali", "Last Name": "Prentice", "Job Title": "SVP, Financial Services", "Organisation": "Fitch Ratings"},
    {"First Name": "Nabil", "Last Name": "Lauder", "Job Title": "VP, Financial Services", "Organisation": "Fitch Ratings"},
    {"First Name": "Venu", "Last Name": "Dumpala", "Job Title": "Head of Solutions, EMEA", "Organisation": "Fitch Ratings"},
    {"First Name": "Richard", "Last Name": "Weston", "Job Title": "Sales Executive - Banking", "Organisation": "Fitch Ratings"},
    {"First Name": "Madhu", "Last Name": "Balasubramanian", "Job Title": "Solution Consultant Specialist", "Organisation": "Fitch Ratings"},
    {"First Name": "Kathleen", "Last Name": "Plunkett", "Job Title": "Director, Banks", "Organisation": "Fitch Ratings"},
    {"First Name": "Ladan", "Last Name": "Ahmed", "Job Title": "Senior Director, Structured Finance", "Organisation": "Fitch Ratings"},
    {"First Name": "Michael", "Last Name": "Bojko", "Job Title": "Director, Banks", "Organisation": "Fitch Ratings"},
    {"First Name": "Duncan", "Last Name": "Paxman", "Job Title": "Senior Director, RMBS - EMEA", "Organisation": "Fitch Ratings"},
    {"First Name": "Leah", "Last Name": "Stewart", "Job Title": "Director", "Organisation": "Fitch Ratings"},
    {"First Name": "Martin", "Last Name": "Orme", "Job Title": "Partner - Audit", "Organisation": "Grant Thornton"},
    {"First Name": "Michael", "Last Name": "Davidson", "Job Title": "Partner - Audit", "Organisation": "Grant Thornton"},
    {"First Name": "Faraaz", "Last Name": "Memon", "Job Title": "Associate Director - Risk Consulting", "Organisation": "Grant Thornton"},
    {"First Name": "Paul", "Last Name": "Hamalainen", "Job Title": "Director - Risk Consulting", "Organisation": "Grant Thornton"},
    {"First Name": "Naveed", "Last Name": "Arshad", "Job Title": "Director - Risk Consulting", "Organisation": "Grant Thornton"},
    {"First Name": "Pierre-Alexandre", "Last Name": "Germont", "Job Title": "Director - Risk Consulting", "Organisation": "Grant Thornton"},
    {"First Name": "Oliver", "Last Name": "Phillips", "Job Title": "Associate Director - Risk Consulting", "Organisation": "Grant Thornton"},
    {"First Name": "Max", "Last Name": "Shepherd", "Job Title": "Group Economist", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Jason", "Last Name": "Vickerman", "Job Title": "Director of Technology Services", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Garth", "Last Name": "Newboult", "Job Title": "Head of AI", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Rich", "Last Name": "Bowles", "Job Title": "Chief Risk Officer", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Vicky", "Last Name": "Oygard", "Job Title": "General Counsel", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Fraser", "Last Name": "Ingram", "Job Title": "Chief Operating Officer", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Louise", "Last Name": "Slater", "Job Title": "Director of Business Risk & Resilience", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Simone", "Last Name": "Fox", "Job Title": "Director of Customer Support", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Tina", "Last Name": "Hughes", "Job Title": "Director of Savings & Digital Channels", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Chris", "Last Name": "Irwin", "Job Title": "Director of Customer Performance", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Simon", "Last Name": "Martin", "Job Title": "Director of Credit Risk", "Organisation": "Yorkshire Building Society"},
    {"First Name": "David", "Last Name": "Wood", "Job Title": "Director Of Enterprise Risk Management", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Jessica", "Last Name": "Sparksman", "Job Title": "Director of Non-Financial Risk", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Daniel", "Last Name": "Macey", "Job Title": "Public Affairs Lead", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Sharon", "Last Name": "Mistry", "Job Title": "Internal Audit Senior Manager", "Organisation": "Yorkshire Building Society"},
    {"First Name": "Trudi", "Last Name": "Flanagan", "Job Title": "Chief Executive Officer", "Organisation": "Zanoo"},
    {"First Name": "Jessica", "Last Name": "Flanagan", "Job Title": "Chief Operating Officer", "Organisation": "Zanoo"}
]
STORAGE_FILE = "networking_progress_v1.csv"

def load_data():
    if os.path.exists(STORAGE_FILE):
        try:
            df = pd.read_csv(STORAGE_FILE)
            # Force Notes to string to prevent TypeError on mobile input
            df['Notes'] = df['Notes'].fillna("").astype(str)
            return df
        except Exception:
            pass
    
    # If no file exists, create new DataFrame from ATTENDEE_DATA
    df = pd.DataFrame(ATTENDEE_DATA)
    df['To Speak'] = False
    df['Met'] = False
    df['Follow Up'] = False
    df['Notes'] = ""
    # Explicitly set the dtype for the Notes column
    df['Notes'] = df['Notes'].astype(str)
    return df

def save_data(df):
    df.to_csv(STORAGE_FILE, index=False)

def main():
    st.set_page_config(page_title="BSA 2026 Networking", layout="centered")
    
    if 'df' not in st.session_state:
        st.session_state.df = load_data()

    st.title("💼 BSA 2026 Networking")
    
    # Persistent Search
    search = st.text_input("Search Name, Role, or Organisation", placeholder="e.g. CRO, Yorkshire, Treasury")
    
    mask = (
        st.session_state.df['First Name'].str.contains(search, case=False) |
        st.session_state.df['Last Name'].str.contains(search, case=False) |
        st.session_state.df['Job Title'].str.contains(search, case=False) |
        st.session_state.df['Organisation'].str.contains(search, case=False)
    )
    filtered = st.session_state.df[mask]

    # Mobile optimized display
    for idx, row in filtered.iterrows():
        # Using a clean format for the expander title
        label = f"{row['First Name']} {row['Last Name']} ({row['Organisation']})"
        with st.expander(label):
            st.write(f"**Role:** {row['Job Title']}")
            
            c1, c2, c3 = st.columns(3)
            # We update session state immediately on change
            st.session_state.df.at[idx, 'Speak To'] = c1.checkbox("Target", value=row['Speak To'], key=f"s_{idx}")
            st.session_state.df.at[idx, 'Spoken To'] = c2.checkbox("Met", value=row['Spoken To'], key=f"m_{idx}")
            st.session_state.df.at[idx, 'Follow Up'] = c3.checkbox("Follow", value=row['Follow Up'], key=f"f_{idx}")
            
            note_val = str(row['Notes']) if pd.notna(row['Notes']) else ""
            st.session_state.df.at[idx, 'Notes'] = st.text_area("Notes", value=note_val, key=f"n_{idx}")
            
            # Save automatically whenever an entry is modified
            save_data(st.session_state.df)

    # Summary and Export in Sidebar
    st.sidebar.header("Progress Tracker")
    targets = st.session_state.df['Speak To'].sum()
    met = st.session_state.df['Spoken To'].sum()
    st.sidebar.metric("Key Targets", targets)
    st.sidebar.metric("Met", met)
    
    st.sidebar.divider()
    csv = st.session_state.df.to_csv(index=False).encode('utf-8')
    st.sidebar.download_button("📥 Export CSV to Phone", data=csv, file_name="BSA_Networking_Final.csv")

if __name__ == "__main__":
    main()
